import Image from 'next/image';
import Head from 'next/head';
import HeaderLink from '../components/HeaderLink';
import logoPic from '../public/logo.png';
import logoPic2 from '../public/logo2.png';
import ExploreIcon from '@mui/icons-material/Explore';
import GroupIcon from '@mui/icons-material/Group';
import OndemandVideoSharpIcon from '@mui/icons-material/OndemandVideoSharp';
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
import ArrowForwardIosRoundedIcon from '@mui/icons-material/ArrowForwardIosRounded';
import { getProviders, signIn } from 'next-auth/react';

function Home({ providers }) {
	console.log(providers);
	return (
		<div className="space-y-5 relative">
			<Head>
				<title>LinkedIn Clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="flex justify-around items-center py-4">
				<div className="relative w-40 h-20 ">
					<Image alt="logo-pic" src={logoPic} layout="fill" objectFit="contain" />
				</div>
				<div className="flex items-center sm:divide-x dividie-gray-300">
					<div className="hidden sm:flex space-x-8 pr-4">
						<HeaderLink Icon={ExploreIcon} text="Discover" />
						<HeaderLink Icon={GroupIcon} text="People" />
						<HeaderLink Icon={OndemandVideoSharpIcon} text="Learning" />
						<HeaderLink Icon={BusinessCenterIcon} text="Jobs" />
					</div>

					{Object.values(providers).map((provider) => (
						<div key={provider.name}>
							<div className="pl-4">
								<button
									className="text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all cursor-pointer hover:bg-blue-700  hover:text-white/100"
									onClick={() => signIn(provider.id, { callbackUrl: '/' })}
								>
									Sign in
								</button>
							</div>
						</div>
					))}

					{/* <div className="pl-4">
						<button className="text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all cursor-pointer hover:bg-blue-700  hover:text-white/100">
							Sign In
						</button>
					</div> */}
				</div>
			</header>
			<main className="flex flex-col xl:flex-row items-center max-w-screen-lg mx-auto">
				<div className="space-y-6 xl:space-y-10">
					<h1 className="pl-4   text-3xl md:text-5xl text-amber-800/80 mx-w-md !leading-snug ">Welcome To your Professional Community</h1>
					<div className="space-y-4">
						<div className="space-y-4">
							<div className="intent">
								<h2 className="text-xl">Search for a job</h2>
								<ArrowForwardIosRoundedIcon className="text-gray-700" />
							</div>
							<div className="intent">
								<h2 className="text-xl">Find a person you know</h2>
								<ArrowForwardIosRoundedIcon className="text-gray-700" />
							</div>
							<div className="intent">
								<h2 className="text-xl">Learn a new skill</h2>
								<ArrowForwardIosRoundedIcon className="text-gray-700" />
							</div>
						</div>
					</div>
				</div>
				<div className="relative  xl:absulate w-80 h-80 xl:w-[750px] xl:h-[450px] top-14 right-1 ">
					<Image alt="logo-pic2" src={logoPic2} layout="fill" priority />
				</div>
			</main>
		</div>
	);
}

export default Home;

export async function getServerSideProps(context) {
	const providers = await getProviders();

	return {
		props: {
			providers,
		},
	};
}
